memory_limit = 256M
allow_url_include = off
display_errors = off
display_startup_errors = off
max_execution_time = 120
session.use_strict_mode = On
realpath_cache_size = 4096k
realpath_cache_ttl = 3600
zend.detect_unicode = Off
[Date]
date.timezone = Europe/Paris

[opcache]
opcache.enable = 1
opcache.memory_consumption = 256
opcache.interned_strings_buffer = 16
opcache.max_accelerated_files = 20000
opcache.validate_timestamps = 1
opcache.revalidate_freq = 0
opcache.enable_cli = 0
