twig:
    default_path: '%kernel.project_dir%/templates'
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        personnageService: '@App\Service\PersonnageService'
        competenceService: '@App\Service\CompetenceService'

when@test:
    twig:
        strict_variables: true
