services:
  frankenphp:
    build:
      context: .
      dockerfile: Dockerfile.frankenphp
    restart: unless-stopped
    ports:
      - "8080:80"    # Port HTTP personnalisé
      - "8443:443"   # Port HTTPS personnalisé (optionnel)
      #- "9000:9000"  # Port pour le mode worker (optionnel)
    volumes:
      - ./:/app
      - ./docker/caddy/Caddyfile:/etc/frankenphp/Caddyfile
    environment:
      - SERVER_NAME=larpmanager.test
      - PHP_EXTENSIONS=pdo,pdo_mysql,intl,ctype,iconv
    depends_on:
      - database
      - mailer


  database:
    image: mysql:8.0
    ports:
      - "30202:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: larpm
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    volumes:
      - ./docker/db/data:/var/lib/mysql:rw # À comenter ou vider pour le premier démarrage
      - ./docker/db/initData:/docker-entrypoint-initdb.d # bootstrap .sql files on first strat

  mailer:
    image: axllent/mailpit
    restart: unless-stopped
    volumes:
      - ./docker/mailpit:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  composer:
    image: composer:latest
    volumes:
      - ./:/app
    working_dir: /app
    command: install
