FROM dunglas/frankenphp:latest

# Installe les dépendances nécessaires pour PDO_MYSQL et INTL
RUN apt-get update && \
    apt-get install -y libonig-dev libxml2-dev libzip-dev && \
    docker-php-ext-configure intl && \
    docker-php-ext-install pdo pdo_mysql intl zip

# Active les extensions
RUN docker-php-ext-enable intl
