services:
    webserver:
        restart: unless-stopped
        ports:
            - "80:80" # HTTP
        depends_on:
            - database
            - mailer

    database:
        image: mysql:8.4
        restart: unless-stopped
        ports:
            - "30202:3306"
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "mysqladmin ping -h 127.0.0.1 -u$${MYSQL_USER:-admin} -p$${MYSQL_PASSWORD:-password}",
                ]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 30s

    mailer:
        image: axllent/mailpit
        restart: unless-stopped
        ports:
            - "8025:8025"
            - "1025:1025"

    # exporter:
    #     image: mysql:8.4
    #     restart: no
    #     entrypoint:
    #         - /bin/sh
    #         - -c
    #         - "chmod -v a+rw /export; docker-entrypoint.sh mysqld"
    #     environment:
    #         EXPORTER_REMOTE_MYSQL_USER: admin
    #         EXPORTER_REMOTE_MYSQL_PASSWORD: password
    #         EXPORTER_REMOTE_MYSQL_HOST: database
    #         EXPORTER_REMOTE_MYSQL_DATABASE: larpm
    #         EXPORTER_FILENAME_SCHEMA: /export/1-initSchema.sql
    #         EXPORTER_FILENAME_DATA: /export/2-insertAnonData.sql
    #         EXPORTER_OBFUSCATE_SQL_FILE: /obfuscate.sql
    #         MYSQL_ROOT_PASSWORD: password
    #         MYSQL_DATABASE: exporter
    #     tmpfs:
    #         - /var/lib/mysql
    #     volumes:
    #         - ./docker/db/export.sh:/docker-entrypoint-initdb.d/99-export.sh:ro
    #         - ./docker/db/obfuscate.sql:/obfuscate.sql:ro
    #         - ./docker/db/export:/export:rw
    #     depends_on:
    #         database:
    #             condition: service_healthy

    #adminer:
    #  image: adminer:5.3.0
    #  restart: always
    #  environment:
    #    ADMINER_DEFAULT_SERVER: database:3306
    #  ports:
    #    - 8081:8080
    #  depends_on:
    #    - database
