services:
    webserver:
        build:
            context: .
            target: dev
            dockerfile: Dockerfile
        env_file:
            - .env.dev
            - .env.dev.local
        volumes:
            - ./:/app # project files
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/zzz-app.ini:ro # custom php.ini
        depends_on:
            - mailer

    database:
        env_file:
            - .env.dev
            - .env.dev.local
        volumes:
            - ./docker/db/initData:/docker-entrypoint-initdb.d:ro # bootstrap .sql files on first start
            - ./docker/db/data:/var/lib/mysql # persistent data

    mailer:
        image: axllent/mailpit:v1.30
        restart: unless-stopped
        ports:
            - "8025:8025"
            - "1025:1025"
        env_file:
            - .env.dev
            - .env.dev.local
        volumes:
            - ./docker/mailpit:/data # persistent data
