services:
    frankenphp:
        build:
            context: .
            dockerfile: Dockerfile.frankenphp
        restart: unless-stopped
        ports:
            - "8080:80"    # Port HTTP personnalisé
            - "8443:443"   # Port HTTPS personnalisé (optionnel)
            #- "9000:9000"  # Port pour le mode worker (optionnel)
        volumes:
            - ./:/app
            - ./docker/caddy/Caddyfile:/etc/frankenphp/Caddyfile
        environment:
            - SERVER_NAME=larpmanager.test
            - PHP_EXTENSIONS=pdo,pdo_mysql,intl,ctype,iconv
        depends_on:
            - database
            - mailer


    database:
        image: mysql:8.4
        ports:
            - "30202:3306"
        restart: unless-stopped
        healthcheck:
            test:
                - "CMD-SHELL"
                - >-
                    mysql --database="$${MYSQL_DATABASE}" --execute="SELECT 1"
                    --user="$${MYSQL_USER}" --password="$${MYSQL_PASSWORD}"
            interval: 5m
            timeout: 5s
            retries: 6
            start_interval: 5s
            start_period: 60s
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: larpm
            MYSQL_USER: admin
            MYSQL_PASSWORD: password
        volumes:
            - database_data:/var/lib/mysql:rw
            - ./docker/db/initData:/docker-entrypoint-initdb.d:ro # bootstrap .sql files on first start

    exporter:
        image: mysql:8.4
        restart: no
        entrypoint:
            - /bin/sh
            - -c
            - "chmod -v a+rw /export; docker-entrypoint.sh mysqld"
        environment:
            EXPORTER_REMOTE_MYSQL_USER: admin
            EXPORTER_REMOTE_MYSQL_PASSWORD: password
            EXPORTER_REMOTE_MYSQL_HOST: database
            EXPORTER_REMOTE_MYSQL_DATABASE: larpm
            EXPORTER_FILENAME_SCHEMA: /export/1-initSchema.sql
            EXPORTER_FILENAME_DATA: /export/2-insertAnonData.sql
            EXPORTER_OBFUSCATE_SQL_FILE: /obfuscate.sql
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: exporter
        tmpfs:
            - /var/lib/mysql
        volumes:
            - ./docker/db/export.sh:/docker-entrypoint-initdb.d/99-export.sh:ro
            - ./docker/db/obfuscate.sql:/obfuscate.sql:ro
            - ./docker/db/export:/export:rw
        depends_on:
            database:
                condition: service_healthy

    #adminer:
    #  image: adminer:5.3.0
    #  restart: always
    #  environment:
    #    ADMINER_DEFAULT_SERVER: database:3306
    #  ports:
    #    - 8081:8080
    #  depends_on:
    #    - database

    mailer:
        image: axllent/mailpit
        restart: unless-stopped
        volumes:
            - ./docker/mailpit:/data
        ports:
            - 8025:8025
            - 1025:1025
        environment:
            MP_MAX_MESSAGES: 5000
            MP_DATA_FILE: /data/mailpit.db
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1

    composer:
        image: composer:latest
        volumes:
            - ./:/app
        working_dir: /app
        command: install

volumes:
    database_data:
