services:
  frankenphp:
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/zzz-app.ini
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "30202:3306"
###< doctrine/doctrine-bundle ###
