services:
###> doctrine/doctrine-bundle ###
  database:
    image: mariadb:11.4.2
    ports:
      - "30202:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: larpm
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    volumes:
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      - ./docker/db/data:/var/lib/mysql:rw
      - ./docker/db/initData:/docker-entrypoint-initdb.d # bootstrap .sql files on first strat
###< doctrine/doctrine-bundle ###

  app:
    build: .
    depends_on:
      - database
      - mailer
    ports:
      - "8082:8000"
    restart: unless-stopped
    volumes:
      - ./:/var/www/html/

  mailer:
    image: axllent/mailpit
    restart: unless-stopped
    volumes:
      - ./docker/mailpit:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
