version: '3.8'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: mariadb:11.2.2
    ports:
      - "30202:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: larpm
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    volumes:
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      - ./docker/db/data:/var/lib/mysql:rw
      - ./docker/db/initData:/docker-entrypoint-initdb.d # bootstrap .sql files on first strat
###< doctrine/doctrine-bundle ###

  app:
    build: .
    depends_on:
      - database
    ports:
      - "8082:8000"
    restart: unless-stopped
    volumes:
      - ./:/var/www/html/

  mailer:
    image: schickling/mailcatcher
    ports: [ 1025, 1080 ]

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
