<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2017-08-02 11:58:23.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping\Column;
use Doctrine\ORM\Mapping\GeneratedValue;
use Doctrine\ORM\Mapping\Id;

/**
 * App\Entity\SecondaryGroup.
 *
 * @Table(name="secondary_group", indexes={@Index(name="fk_secondary_groupe_secondary_group_type1_idx", columns={"secondary_group_type_id"}), @Index(name="fk_secondary_group_personnage1_idx", columns={"personnage_id"}), @Index(name="fk_secondary_group_topic1_idx", columns={"topic_id"})})
 *
 * @InheritanceType("SINGLE_TABLE")
 *
 * @DiscriminatorColumn(name="discr", type="string")
 *
 * @DiscriminatorMap({"base":"BaseSecondaryGroup", "extended":"SecondaryGroup"})
 */
class BaseSecondaryGroup
{
    #[Id, Column(type: \Doctrine\DBAL\Types\Types::INTEGER, options: ['unsigned' => true]), GeneratedValue(strategy: 'AUTO')]
    protected ?int $id = null;

    /**
     * @Column(type="string", length=45)
     */
    protected $label;

    /**
     * @Column(type="text", nullable=true)
     */
    protected $description;

    /**
     * @Column(type="text", nullable=true)
     */
    protected $description_secrete;

    /**
     * @Column(type="boolean", nullable=true)
     */
    protected $secret;

    /**
     * @Column(type="text", nullable=true)
     */
    protected $materiel;

    /**
     * @OneToMany(targetEntity="IntrigueHasGroupeSecondaire", mappedBy="secondaryGroup")
     *
     * @JoinColumn(name="id", referencedColumnName="secondary_group_id", nullable=false)
     */
    protected $intrigueHasGroupeSecondaires;

    /**
     * @OneToMany(targetEntity="Membre", mappedBy="secondaryGroup")
     *
     * @JoinColumn(name="id", referencedColumnName="secondary_group_id", nullable=false)
     *
     * @OrderBy({"id" = "ASC",})
     */
    protected $membres;

    /**
     * @OneToMany(targetEntity="Postulant", mappedBy="secondaryGroup")
     *
     * @JoinColumn(name="id", referencedColumnName="secondary_group_id", nullable=false)
     */
    protected $postulants;

    /**
     * @ManyToOne(targetEntity="SecondaryGroupType", inversedBy="secondaryGroups")
     *
     * @JoinColumn(name="secondary_group_type_id", referencedColumnName="id", nullable=false)
     */
    protected $secondaryGroupType;

    /**
     * @ManyToOne(targetEntity="Personnage", inversedBy="secondaryGroups")
     *
     * @JoinColumn(name="personnage_id", referencedColumnName="id")
     */
    protected $personnage;

    /**
     * @ManyToOne(targetEntity="Topic", inversedBy="secondaryGroups")
     *
     * @JoinColumn(name="topic_id", referencedColumnName="id", nullable=false)
     */
    protected $topic;

    public function __construct()
    {
        $this->intrigueHasGroupeSecondaires = new ArrayCollection();
        $this->membres = new ArrayCollection();
        $this->postulants = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param int $id
     *
     * @return \App\Entity\SecondaryGroup
     */
    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * Set the value of label.
     *
     * @param string $label
     *
     * @return \App\Entity\SecondaryGroup
     */
    public function setLabel(string $label): static
    {
        $this->label = $label;

        return $this;
    }

    /**
     * Get the value of label.
     *
     * @return string
     */
    public function getLabel(): string
    {
        return $this->label ?? '';
    }

    /**
     * Set the value of description.
     *
     * @param string $description
     *
     * @return \App\Entity\SecondaryGroup
     */
    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get the value of description.
     *
     * @return string
     */
    public function getDescription(): string
    {
        return $this->description ?? '';
    }

    /**
     * Set the value of description_secrete.
     *
     * @param string $description_secrete
     *
     * @return \App\Entity\SecondaryGroup
     */
    public function setDescriptionSecrete($description_secrete)
    {
        $this->description_secrete = $description_secrete;

        return $this;
    }

    /**
     * Get the value of description_secrete.
     *
     * @return string
     */
    public function getDescriptionSecrete()
    {
        return $this->description_secrete;
    }

    /**
     * Set the value of secret.
     *
     * @param bool $secret
     *
     * @return \App\Entity\SecondaryGroup
     */
    public function setSecret($secret)
    {
        $this->secret = $secret;

        return $this;
    }

    /**
     * Get the value of secret.
     *
     * @return bool
     */
    public function getSecret()
    {
        return $this->secret;
    }

    /**
     * Set the value of materiel.
     *
     * @param string $materiel
     *
     * @return \App\Entity\SecondaryGroup
     */
    public function setMateriel($materiel)
    {
        $this->materiel = $materiel;

        return $this;
    }

    /**
     * Get the value of materiel.
     *
     * @return string
     */
    public function getMateriel()
    {
        return $this->materiel;
    }

    /**
     * Add IntrigueHasGroupeSecondaire entity to collection (one to many).
     *
     * @return \App\Entity\SecondaryGroup
     */
    public function addIntrigueHasGroupeSecondaire(IntrigueHasGroupeSecondaire $intrigueHasGroupeSecondaire)
    {
        $this->intrigueHasGroupeSecondaires[] = $intrigueHasGroupeSecondaire;

        return $this;
    }

    /**
     * Remove IntrigueHasGroupeSecondaire entity from collection (one to many).
     *
     * @return \App\Entity\SecondaryGroup
     */
    public function removeIntrigueHasGroupeSecondaire(IntrigueHasGroupeSecondaire $intrigueHasGroupeSecondaire)
    {
        $this->intrigueHasGroupeSecondaires->removeElement($intrigueHasGroupeSecondaire);

        return $this;
    }

    /**
     * Get IntrigueHasGroupeSecondaire entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getIntrigueHasGroupeSecondaires()
    {
        return $this->intrigueHasGroupeSecondaires;
    }

    /**
     * Add Membre entity to collection (one to many).
     *
     * @return \App\Entity\SecondaryGroup
     */
    public function addMembre(Membre $membre)
    {
        $this->membres[] = $membre;

        return $this;
    }

    /**
     * Remove Membre entity from collection (one to many).
     *
     * @return \App\Entity\SecondaryGroup
     */
    public function removeMembre(Membre $membre)
    {
        $this->membres->removeElement($membre);

        return $this;
    }

    /**
     * Get Membre entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getMembres()
    {
        return $this->membres;
    }

    /**
     * Add Postulant entity to collection (one to many).
     *
     * @return \App\Entity\SecondaryGroup
     */
    public function addPostulant(Postulant $postulant)
    {
        $this->postulants[] = $postulant;

        return $this;
    }

    /**
     * Remove Postulant entity from collection (one to many).
     *
     * @return \App\Entity\SecondaryGroup
     */
    public function removePostulant(Postulant $postulant)
    {
        $this->postulants->removeElement($postulant);

        return $this;
    }

    /**
     * Get Postulant entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getPostulants()
    {
        return $this->postulants;
    }

    /**
     * Set SecondaryGroupType entity (many to one).
     *
     * @return \App\Entity\SecondaryGroup
     */
    public function setSecondaryGroupType(SecondaryGroupType $secondaryGroupType = null)
    {
        $this->secondaryGroupType = $secondaryGroupType;

        return $this;
    }

    /**
     * Get SecondaryGroupType entity (many to one).
     *
     * @return \App\Entity\SecondaryGroupType
     */
    public function getSecondaryGroupType()
    {
        return $this->secondaryGroupType;
    }

    /**
     * Set Personnage entity (many to one).
     *
     * @return \App\Entity\SecondaryGroup
     */
    public function setPersonnage(Personnage $personnage = null)
    {
        $this->personnage = $personnage;

        return $this;
    }

    /**
     * Get Personnage entity (many to one).
     *
     * @return \App\Entity\Personnage
     */
    public function getPersonnage()
    {
        return $this->personnage;
    }

    /**
     * Set Topic entity (many to one).
     *
     * @return \App\Entity\SecondaryGroup
     */
    public function setTopic(Topic $topic = null)
    {
        $this->topic = $topic;

        return $this;
    }

    /**
     * Get Topic entity (many to one).
     *
     * @return \App\Entity\Topic
     */
    public function getTopic()
    {
        return $this->topic;
    }

    public function __sleep()
    {
        return ['id', 'label', 'description', 'secondary_group_type_id', 'personnage_id', 'topic_id', 'description_secrete', 'secret', 'materiel'];
    }
}
