<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2017-02-09 11:20:18.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;

/**
 * App\Entity\Level
 *
 * @Table(name="`level`")
 * @InheritanceType("SINGLE_TABLE")
 * @DiscriminatorColumn(name="discr", type="string")
 * @DiscriminatorMap({"base":"BaseLevel", "extended":"Level"})
 */
class BaseLevel
{
    /**
     * @Id
     * @Column(type="integer")
     * @GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @Column(name="`index`", type="integer")
     */
    protected $index;

    /**
     * @Column(type="string", length=45)
     */
    protected $label;

    /**
     * @Column(type="integer", nullable=true)
     */
    protected $cout;

    /**
     * @Column(type="integer", nullable=true)
     */
    protected $cout_favori;

    /**
     * @Column(type="integer", nullable=true)
     */
    protected $cout_meconu;

    /**
     * @OneToMany(targetEntity="Competence", mappedBy="level", cascade={"persist"})
     * @JoinColumn(name="id", referencedColumnName="level_id", nullable=false)
     */
    protected $competences;

    public function __construct()
    {
        $this->competences = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \App\Entity\Level
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of index.
     *
     * @param integer $index
     * @return \App\Entity\Level
     */
    public function setIndex($index)
    {
        $this->index = $index;

        return $this;
    }

    /**
     * Get the value of index.
     *
     * @return integer
     */
    public function getIndex()
    {
        return $this->index;
    }

    /**
     * Set the value of label.
     *
     * @param string $label
     * @return \App\Entity\Level
     */
    public function setLabel($label)
    {
        $this->label = $label;

        return $this;
    }

    /**
     * Get the value of label.
     *
     * @return string
     */
    public function getLabel()
    {
        return $this->label;
    }

    /**
     * Set the value of cout.
     *
     * @param integer $cout
     * @return \App\Entity\Level
     */
    public function setCout($cout)
    {
        $this->cout = $cout;

        return $this;
    }

    /**
     * Get the value of cout.
     *
     * @return integer
     */
    public function getCout()
    {
        return $this->cout;
    }

    /**
     * Set the value of cout_favori.
     *
     * @param integer $cout_favori
     * @return \App\Entity\Level
     */
    public function setCoutFavori($cout_favori)
    {
        $this->cout_favori = $cout_favori;

        return $this;
    }

    /**
     * Get the value of cout_favori.
     *
     * @return integer
     */
    public function getCoutFavori()
    {
        return $this->cout_favori;
    }

    /**
     * Set the value of cout_meconu.
     *
     * @param integer $cout_meconu
     * @return \App\Entity\Level
     */
    public function setCoutMeconu($cout_meconu)
    {
        $this->cout_meconu = $cout_meconu;

        return $this;
    }

    /**
     * Get the value of cout_meconu.
     *
     * @return integer
     */
    public function getCoutMeconu()
    {
        return $this->cout_meconu;
    }

    /**
     * Add Competence entity to collection (one to many).
     *
     * @param \App\Entity\Competence $competence
     * @return \App\Entity\Level
     */
    public function addCompetence(Competence $competence)
    {
        $this->competences[] = $competence;

        return $this;
    }

    /**
     * Remove Competence entity from collection (one to many).
     *
     * @param \App\Entity\Competence $competence
     * @return \App\Entity\Level
     */
    public function removeCompetence(Competence $competence)
    {
        $this->competences->removeElement($competence);

        return $this;
    }

    /**
     * Get Competence entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getCompetences()
    {
        return $this->competences;
    }

    public function __sleep()
    {
        return array('id', 'index', 'label', 'cout', 'cout_favori', 'cout_meconu');
    }
}