<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2017-05-02 11:53:35.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace App\Entity;

/**
 * App\Entity\PugilatHistory.
 *
 * @Table(name="pugilat_history", indexes={@Index(name="fk_pugilat_history_personnage1_idx", columns={"personnage_id"})})
 *
 * @InheritanceType("SINGLE_TABLE")
 *
 * @DiscriminatorColumn(name="discr", type="string")
 *
 * @DiscriminatorMap({"base":"BasePugilatHistory", "extended":"PugilatHistory"})
 */
class BasePugilatHistory
{
    /**
     * @Id
     *
     * @Column(type="integer", options={"unsigned":true})
     *
     * @GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @Column(name="`date`", type="date")
     */
    protected $date;

    /**
     * @Column(type="integer")
     */
    protected $pugilat;

    /**
     * @Column(type="text")
     */
    protected $explication;

    /**
     * @ManyToOne(targetEntity="Personnage", inversedBy="pugilatHistories")
     *
     * @JoinColumn(name="personnage_id", referencedColumnName="id", nullable=false)
     */
    protected $personnage;

    public function __construct()
    {
    }

    /**
     * Set the value of id.
     *
     * @param int $id
     *
     * @return \App\Entity\PugilatHistory
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of date.
     *
     * @param \DateTime $date
     *
     * @return \App\Entity\PugilatHistory
     */
    public function setDate($date)
    {
        $this->date = $date;

        return $this;
    }

    /**
     * Get the value of date.
     *
     * @return \DateTime
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * Set the value of pugilat.
     *
     * @param int $pugilat
     *
     * @return \App\Entity\PugilatHistory
     */
    public function setPugilat($pugilat)
    {
        $this->pugilat = $pugilat;

        return $this;
    }

    /**
     * Get the value of pugilat.
     *
     * @return int
     */
    public function getPugilat()
    {
        return $this->pugilat;
    }

    /**
     * Set the value of explication.
     *
     * @param string $explication
     *
     * @return \App\Entity\PugilatHistory
     */
    public function setExplication($explication)
    {
        $this->explication = $explication;

        return $this;
    }

    /**
     * Get the value of explication.
     *
     * @return string
     */
    public function getExplication()
    {
        return $this->explication;
    }

    /**
     * Set Personnage entity (many to one).
     *
     * @return \App\Entity\PugilatHistory
     */
    public function setPersonnage(Personnage $personnage = null)
    {
        $this->personnage = $personnage;

        return $this;
    }

    /**
     * Get Personnage entity (many to one).
     *
     * @return \App\Entity\Personnage
     */
    public function getPersonnage()
    {
        return $this->personnage;
    }

    public function __sleep()
    {
        return ['id', 'date', 'pugilat', 'explication', 'personnage_id'];
    }
}
