<?php

/**
 * Generated by Kevin F.
 */

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping\Column;
use Doctrine\ORM\Mapping\GeneratedValue;
use Doctrine\ORM\Mapping\Id;

/**
 * App\Entity\GroupeGnOrdre.
 *
 * @Table(name="groupe_gn_ordre")
 *
 * @InheritanceType("SINGLE_TABLE")
 *
 * @DiscriminatorColumn(name="discr", type="string")
 *
 * @DiscriminatorMap({"base":"BaseGroupeGnOrdre", "extended":"GroupeGnOrdre"})
 */
class BaseGroupeGnOrdre
{
    /**
     * @var \Doctrine\Common\Collections\ArrayCollection
     */
    public $participants;
    public $groupeGn;

    #[Id, Column(type: \Doctrine\DBAL\Types\Types::INTEGER, options: ['unsigned' => true]), GeneratedValue(strategy: 'AUTO')]
    protected ?int $id = null;

    /**
     * @Column(name="`ordre`", type="string")
     */
    protected $ordre;

    /**
     * @Column(name="`extra`", type="string")
     */
    protected $extra;

    /**
     * @ManyToOne(targetEntity="GroupeGn", inversedBy="groupeGnOrdre")
     *
     * @JoinColumn(name="groupe_gn_id", referencedColumnName="id", nullable=false)
     */
    protected $groupe_gn;

    /**
     * @ManyToOne(targetEntity="Territoire", inversedBy="groupeGnOrdre")
     *
     * @JoinColumn(name="cible_id", referencedColumnName="id")
     */
    protected $cible;

    public function __construct()
    {
        $this->participants = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param int $id
     *
     * @return \App\Entity\GroupeGnOrdre
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of ordre.
     *
     * @param bool $ordre
     *
     * @return \App\Entity\GroupeGnOrdre
     */
    public function setOrdre($ordre)
    {
        $this->ordre = $ordre;

        return $this;
    }

    /**
     * Get the value of ordre.
     *
     * @return bool
     */
    public function getOrdre()
    {
        return $this->ordre;
    }

    /**
     * Set the value of extra.
     *
     * @param bool $extra
     *
     * @return \App\Entity\GroupeGnOrdre
     */
    public function setExtra($extra)
    {
        $this->extra = $extra;

        return $this;
    }

    /**
     * Get the value of extra.
     *
     * @return bool
     */
    public function getExtra()
    {
        return $this->extra;
    }

    /**
     * Set the value of cible.
     *
     * @param bool $cible
     *
     * @return \App\Entity\GroupeGnOrdre
     */
    public function setCible($cible)
    {
        $this->cible = $cible;

        return $this;
    }

    /**
     * Get Territoire entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getCible()
    {
        return $this->cible;
    }

    /**
     * Set GroupeGn entity (many to one).
     *
     * @return \App\Entity\GroupeGnOrdre
     */
    public function setGroupeGN(GroupeGN $groupeGN)
    {
        $this->groupeGn = $groupeGn;

        return $this;
    }

    /**
     * Get GroupeGn entity (many to one).
     *
     * @return \App\Entity\GroupeGn
     */
    public function getGroupeGn()
    {
        return $this->groupeGn;
    }

    public function __sleep()
    {
        return ['id', 'ordre', 'groupe_gn_id', 'cible_id'];
    }
}
