<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2017-02-09 11:20:20.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace App\Entity;

/**
 * App\Entity\QualityValeur.
 *
 * @Table(name="quality_valeur", indexes={@Index(name="fk_quality_valeur_qualite1_idx", columns={"quality_id"}), @Index(name="fk_quality_valeur_monnaie1_idx", columns={"monnaie_id"})})
 *
 * @InheritanceType("SINGLE_TABLE")
 *
 * @DiscriminatorColumn(name="discr", type="string")
 *
 * @DiscriminatorMap({"base":"BaseQualityValeur", "extended":"QualityValeur"})
 */
class BaseQualityValeur
{
    /**
     * @Id
     *
     * @Column(type="integer", options={"unsigned":true})
     *
     * @GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @Column(type="integer")
     */
    protected $nombre;

    /**
     * @ManyToOne(targetEntity="Quality", inversedBy="qualityValeurs", cascade={"persist", "remove"})
     *
     * @JoinColumn(name="quality_id", referencedColumnName="id", nullable=false)
     */
    protected $quality;

    /**
     * @ManyToOne(targetEntity="Monnaie", inversedBy="qualityValeurs")
     *
     * @JoinColumn(name="monnaie_id", referencedColumnName="id", nullable=false)
     */
    protected $monnaie;

    public function __construct()
    {
    }

    /**
     * Set the value of id.
     *
     * @param int $id
     *
     * @return \App\Entity\QualityValeur
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of nombre.
     *
     * @param int $nombre
     *
     * @return \App\Entity\QualityValeur
     */
    public function setNombre($nombre)
    {
        $this->nombre = $nombre;

        return $this;
    }

    /**
     * Get the value of nombre.
     *
     * @return int
     */
    public function getNombre()
    {
        return $this->nombre;
    }

    /**
     * Set Quality entity (many to one).
     *
     * @return \App\Entity\QualityValeur
     */
    public function setQuality(Quality $quality = null)
    {
        $this->quality = $quality;

        return $this;
    }

    /**
     * Get Quality entity (many to one).
     *
     * @return \App\Entity\Quality
     */
    public function getQuality()
    {
        return $this->quality;
    }

    /**
     * Set Monnaie entity (many to one).
     *
     * @return \App\Entity\QualityValeur
     */
    public function setMonnaie(Monnaie $monnaie = null)
    {
        $this->monnaie = $monnaie;

        return $this;
    }

    /**
     * Get Monnaie entity (many to one).
     *
     * @return \App\Entity\Monnaie
     */
    public function getMonnaie()
    {
        return $this->monnaie;
    }

    public function __sleep()
    {
        return ['id', 'quality_id', 'monnaie_id', 'nombre'];
    }
}
