<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2017-02-09 11:20:22.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping\Column;
use Doctrine\ORM\Mapping\GeneratedValue;
use Doctrine\ORM\Mapping\Id;

/**
 * App\Entity\Titre.
 *
 * @Table(name="titre")
 *
 * @InheritanceType("SINGLE_TABLE")
 *
 * @DiscriminatorColumn(name="discr", type="string")
 *
 * @DiscriminatorMap({"base":"BaseTitre", "extended":"Titre"})
 */
class BaseTitre
{
    #[Id, Column(type: \Doctrine\DBAL\Types\Types::INTEGER, options: ['unsigned' => true]), GeneratedValue(strategy: 'AUTO')]
    protected ?int $id = null;

    /**
     * @Column(type="string", length=45)
     */
    protected $label;

    /**
     * @Column(type="integer")
     */
    protected $renomme;

    /**
     * @OneToMany(targetEntity="TitreTerritoire", mappedBy="titre")
     *
     * @JoinColumn(name="id", referencedColumnName="titre_id", nullable=false)
     */
    protected $titreTerritoires;

    public function __construct()
    {
        $this->titreTerritoires = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param int $id
     *
     * @return \App\Entity\Titre
     */
    public function setId($id): static
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of label.
     *
     * @param string $label
     *
     * @return \App\Entity\Titre
     */
    public function setLabel($label)
    {
        $this->label = $label;

        return $this;
    }

    /**
     * Get the value of label.
     *
     * @return string
     */
    public function getLabel()
    {
        return $this->label;
    }

    /**
     * Set the value of renomme.
     *
     * @param int $renomme
     *
     * @return \App\Entity\Titre
     */
    public function setRenomme($renomme)
    {
        $this->renomme = $renomme;

        return $this;
    }

    /**
     * Get the value of renomme.
     *
     * @return int
     */
    public function getRenomme()
    {
        return $this->renomme;
    }

    /**
     * Add TitreTerritoire entity to collection (one to many).
     *
     * @return \App\Entity\Titre
     */
    public function addTitreTerritoire(TitreTerritoire $titreTerritoire)
    {
        $this->titreTerritoires[] = $titreTerritoire;

        return $this;
    }

    /**
     * Remove TitreTerritoire entity from collection (one to many).
     *
     * @return \App\Entity\Titre
     */
    public function removeTitreTerritoire(TitreTerritoire $titreTerritoire)
    {
        $this->titreTerritoires->removeElement($titreTerritoire);

        return $this;
    }

    /**
     * Get TitreTerritoire entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getTitreTerritoires()
    {
        return $this->titreTerritoires;
    }

    public function __sleep()
    {
        return ['id', 'label', 'renomme'];
    }
}
