<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2017-02-09 11:20:19.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping\Column;
use Doctrine\ORM\Mapping\GeneratedValue;
use Doctrine\ORM\Mapping\Id;

/**
 * App\Entity\PersonnageSecondaire.
 *
 * @Table(name="personnage_secondaire", indexes={@Index(name="fk_personnage_secondaire_classe1_idx", columns={"classe_id"})})
 *
 * @InheritanceType("SINGLE_TABLE")
 *
 * @DiscriminatorColumn(name="discr", type="string")
 *
 * @DiscriminatorMap({"base":"BasePersonnageSecondaire", "extended":"PersonnageSecondaire"})
 */
class BasePersonnageSecondaire
{
    #[Id, Column(type: \Doctrine\DBAL\Types\Types::INTEGER, options: ['unsigned' => true]), GeneratedValue(strategy: 'AUTO')]
    protected ?int $id = null;

    /**
     * @OneToMany(targetEntity="Participant", mappedBy="personnageSecondaire")
     *
     * @JoinColumn(name="id", referencedColumnName="personnage_secondaire_id", nullable=false)
     */
    protected $participants;

    /**
     * @OneToMany(targetEntity="PersonnageSecondaireCompetence", mappedBy="personnageSecondaire", cascade={"persist"})
     *
     * @JoinColumn(name="id", referencedColumnName="personnage_secondaire_id", nullable=false)
     */
    protected $personnageSecondaireCompetences;

    /**
     * @OneToMany(targetEntity="User", mappedBy="personnageSecondaire", cascade={"persist", "remove"})
     *
     * @JoinColumn(name="id", referencedColumnName="personnage_secondaire_id", nullable=false)
     */
    protected $Users;

    /**
     * @ManyToOne(targetEntity="Classe", inversedBy="personnageSecondaires")
     *
     * @JoinColumn(name="classe_id", referencedColumnName="id", nullable=false)
     */
    protected $classe;

    public function __construct()
    {
        $this->participants = new ArrayCollection();
        $this->personnageSecondaireCompetences = new ArrayCollection();
        $this->Users = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param int $id
     *
     * @return \App\Entity\PersonnageSecondaire
     */
    public function setId($id): static
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Add Participant entity to collection (one to many).
     *
     * @return \App\Entity\PersonnageSecondaire
     */
    public function addParticipant(Participant $participant)
    {
        $this->participants[] = $participant;

        return $this;
    }

    /**
     * Remove Participant entity from collection (one to many).
     *
     * @return \App\Entity\PersonnageSecondaire
     */
    public function removeParticipant(Participant $participant)
    {
        $this->participants->removeElement($participant);

        return $this;
    }

    /**
     * Get Participant entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getParticipants()
    {
        return $this->participants;
    }

    /**
     * Add PersonnageSecondaireCompetence entity to collection (one to many).
     *
     * @return \App\Entity\PersonnageSecondaire
     */
    public function addPersonnageSecondaireCompetence(PersonnageSecondaireCompetence $personnageSecondaireCompetence)
    {
        $this->personnageSecondaireCompetences[] = $personnageSecondaireCompetence;

        return $this;
    }

    /**
     * Remove PersonnageSecondaireCompetence entity from collection (one to many).
     *
     * @return \App\Entity\PersonnageSecondaire
     */
    public function removePersonnageSecondaireCompetence(PersonnageSecondaireCompetence $personnageSecondaireCompetence)
    {
        $this->personnageSecondaireCompetences->removeElement($personnageSecondaireCompetence);

        return $this;
    }

    /**
     * Get PersonnageSecondaireCompetence entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getPersonnageSecondaireCompetences()
    {
        return $this->personnageSecondaireCompetences;
    }

    /**
     * Add User entity to collection (one to many).
     *
     * @return \App\Entity\PersonnageSecondaire
     */
    public function addUser(User $User)
    {
        $this->Users[] = $User;

        return $this;
    }

    /**
     * Remove User entity from collection (one to many).
     *
     * @return \App\Entity\PersonnageSecondaire
     */
    public function removeUser(User $User)
    {
        $this->Users->removeElement($User);

        return $this;
    }

    /**
     * Get User entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getUsers()
    {
        return $this->Users;
    }

    /**
     * Set Classe entity (many to one).
     *
     * @return \App\Entity\PersonnageSecondaire
     */
    public function setClasse(Classe $classe = null)
    {
        $this->classe = $classe;

        return $this;
    }

    /**
     * Get Classe entity (many to one).
     *
     * @return \App\Entity\Classe
     */
    public function getClasse()
    {
        return $this->classe;
    }

    public function __sleep()
    {
        return ['id', 'classe_id'];
    }
}
