<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2017-02-09 11:20:16.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;

/**
 * App\Entity\EtatCivil.
 *
 * @Table(name="etat_civil")
 * @InheritanceType("SINGLE_TABLE")
 * @DiscriminatorColumn(name="discr", type="string")
 * @DiscriminatorMap({"base":"BaseEtatCivil", "extended":"EtatCivil"})
 */
class BaseEtatCivil
{
    /**
     * @var \Doctrine\Common\Collections\ArrayCollection
     */
    public $Users;
    /**
     * @Id
     *
     * @Column(type="integer")
     *
     * @GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @Column(type="string", length=45, nullable=true)
     */
    protected $nom;

    /**
     * @Column(type="string", length=45, nullable=true)
     */
    protected $prenom;

    /**
     * @Column(type="string", length=45, nullable=true)
     */
    protected $prenom_usage;

    /**
     * @Column(type="string", length=45, nullable=true)
     */
    protected $telephone;

    /**
     * @Column(type="string", length=45, nullable=true)
     */
    protected $photo;

    /**
     * @Column(type="datetime", nullable=true)
     */
    protected $date_naissance;

    /**
     * @Column(type="text", nullable=true)
     */
    protected $probleme_medicaux;

    /**
     * @Column(type="string", length=45, nullable=true)
     */
    protected $personne_a_prevenir;

    /**
     * @Column(type="string", length=45, nullable=true)
     */
    protected $tel_pap;

    /**
     * @Column(type="string", length=45, nullable=true)
     */
    protected $fedegn;

    /**
     * @Column(type="datetime")
     */
    protected $creation_date;

    /**
     * @Column(type="datetime")
     */
    protected $update_date;

    /**
     * @OneToOne(targetEntity="User", mappedBy="etatCivil", cascade={"persist", "remove"})
     */
    protected $User;

    public function __construct()
    {
        $this->Users = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param int $id
     *
     * @return \App\Entity\EtatCivil
     */
    public function setId($id): static
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of nom.
     *
     * @param string $nom
     *
     * @return \App\Entity\EtatCivil
     */
    public function setNom($nom)
    {
        $this->nom = $nom;

        return $this;
    }

    /**
     * Get the value of nom.
     *
     * @return string
     */
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * Set the value of prenom.
     *
     * @param string $prenom
     *
     * @return \App\Entity\EtatCivil
     */
    public function setPrenom($prenom)
    {
        $this->prenom = $prenom;

        return $this;
    }

    /**
     * Get the value of prenom.
     *
     * @return string
     */
    public function getPrenom()
    {
        return $this->prenom;
    }

    /**
     * Set the value of prenom_usage.
     *
     * @param string $prenom_usage
     *
     * @return \App\Entity\EtatCivil
     */
    public function setPrenomUsage($prenom_usage)
    {
        $this->prenom_usage = $prenom_usage;

        return $this;
    }

    /**
     * Get the value of prenom_usage.
     *
     * @return string
     */
    public function getPrenomUsage()
    {
        return $this->prenom_usage;
    }

    /**
     * Set the value of telephone.
     *
     * @param string $telephone
     *
     * @return \App\Entity\EtatCivil
     */
    public function setTelephone($telephone)
    {
        $this->telephone = $telephone;

        return $this;
    }

    /**
     * Get the value of telephone.
     *
     * @return string
     */
    public function getTelephone()
    {
        return $this->telephone;
    }

    /**
     * Set the value of photo.
     *
     * @param string $photo
     *
     * @return \App\Entity\EtatCivil
     */
    public function setPhoto($photo)
    {
        $this->photo = $photo;

        return $this;
    }

    /**
     * Get the value of photo.
     *
     * @return string
     */
    public function getPhoto()
    {
        return $this->photo;
    }

    /**
     * Set the value of date_naissance.
     *
     * @param \DateTime $date_naissance
     *
     * @return \App\Entity\EtatCivil
     */
    public function setDateNaissance($date_naissance)
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }

    /**
     * Get the value of date_naissance.
     *
     * @return \DateTime
     */
    public function getDateNaissance()
    {
        return $this->date_naissance;
    }

    /**
     * Set the value of probleme_medicaux.
     *
     * @param string $probleme_medicaux
     *
     * @return \App\Entity\EtatCivil
     */
    public function setProblemeMedicaux($probleme_medicaux)
    {
        $this->probleme_medicaux = $probleme_medicaux;

        return $this;
    }

    /**
     * Get the value of probleme_medicaux.
     *
     * @return string
     */
    public function getProblemeMedicaux()
    {
        return $this->probleme_medicaux;
    }

    /**
     * Set the value of personne_a_prevenir.
     *
     * @param string $personne_a_prevenir
     *
     * @return \App\Entity\EtatCivil
     */
    public function setPersonneAPrevenir($personne_a_prevenir)
    {
        $this->personne_a_prevenir = $personne_a_prevenir;

        return $this;
    }

    /**
     * Get the value of personne_a_prevenir.
     *
     * @return string
     */
    public function getPersonneAPrevenir()
    {
        return $this->personne_a_prevenir;
    }

    /**
     * Set the value of tel_pap.
     *
     * @param string $tel_pap
     *
     * @return \App\Entity\EtatCivil
     */
    public function setTelPap($tel_pap)
    {
        $this->tel_pap = $tel_pap;

        return $this;
    }

    /**
     * Get the value of tel_pap.
     *
     * @return string
     */
    public function getTelPap()
    {
        return $this->tel_pap;
    }

    /**
     * Set the value of fedegn.
     *
     * @param string $fedegn
     *
     * @return \App\Entity\EtatCivil
     */
    public function setFedegn($fedegn)
    {
        $this->fedegn = $fedegn;

        return $this;
    }

    /**
     * Get the value of fedegn.
     *
     * @return string
     */
    public function getFedegn()
    {
        return $this->fedegn;
    }

    /**
     * Set the value of creation_date.
     *
     * @param \DateTime $creation_date
     *
     * @return \App\Entity\EtatCivil
     */
    public function setCreationDate($creation_date)
    {
        $this->creation_date = $creation_date;

        return $this;
    }

    /**
     * Get the value of creation_date.
     *
     * @return \DateTime
     */
    public function getCreationDate()
    {
        return $this->creation_date;
    }

    /**
     * Set the value of update_date.
     *
     * @param \DateTime $update_date
     *
     * @return \App\Entity\EtatCivil
     */
    public function setUpdateDate($update_date)
    {
        $this->update_date = $update_date;

        return $this;
    }

    /**
     * Get the value of update_date.
     *
     * @return \DateTime
     */
    public function getUpdateDate()
    {
        return $this->update_date;
    }

    /**
     * Set User entity (one to one).
     *
     * @return \App\Entity\EtatCivil
     */
    public function setUser(User $User = null)
    {
        $User->setEtatCivil($this);
        $this->User = $User;

        return $this;
    }

    /**
     * Get User entity (one to one).
     *
     * @return \App\Entity\User
     */
    public function getUser()
    {
        return $this->User;
    }

    public function __sleep()
    {
        return ['id', 'nom', 'prenom', 'prenom_usage', 'telephone', 'photo', 'date_naissance', 'probleme_medicaux', 'personne_a_prevenir', 'tel_pap', 'fedegn', 'creation_date', 'update_date'];
    }
}