<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2017-07-04 11:25:50.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace App\Entity;

/**
 * App\Entity\Reponse.
 *
 * @Table(name="reponse", indexes={@Index(name="fk_reponse_idx", columns={"question_id"}), @Index(name="fk_reponse_participant1_idx", columns={"participant_id"})})
 *
 * @InheritanceType("SINGLE_TABLE")
 *
 * @DiscriminatorColumn(name="discr", type="string")
 *
 * @DiscriminatorMap({"base":"BaseReponse", "extended":"Reponse"})
 */
class BaseReponse
{
    /**
     * @Id
     *
     * @Column(type="integer", options={"unsigned":true})
     *
     * @GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @Column(type="string", length=45)
     */
    protected $reponse;

    /**
     * @ManyToOne(targetEntity="Question", inversedBy="reponses")
     *
     * @JoinColumn(name="question_id", referencedColumnName="id", nullable=false)
     */
    protected $question;

    /**
     * @ManyToOne(targetEntity="Participant", inversedBy="reponses")
     *
     * @JoinColumn(name="participant_id", referencedColumnName="id", nullable=false)
     */
    protected $participant;

    public function __construct()
    {
    }

    /**
     * Set the value of id.
     *
     * @param int $id
     *
     * @return \App\Entity\Reponse
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of reponse.
     *
     * @param string $reponse
     *
     * @return \App\Entity\Reponse
     */
    public function setReponse($reponse)
    {
        $this->reponse = $reponse;

        return $this;
    }

    /**
     * Get the value of reponse.
     *
     * @return string
     */
    public function getReponse()
    {
        return $this->reponse;
    }

    /**
     * Set Question entity (many to one).
     *
     * @return \App\Entity\Reponse
     */
    public function setQuestion(Question $question = null)
    {
        $this->question = $question;

        return $this;
    }

    /**
     * Get Question entity (many to one).
     *
     * @return \App\Entity\Question
     */
    public function getQuestion()
    {
        return $this->question;
    }

    /**
     * Set Participant entity (many to one).
     *
     * @return \App\Entity\Reponse
     */
    public function setParticipant(Participant $participant = null)
    {
        $this->participant = $participant;

        return $this;
    }

    /**
     * Get Participant entity (many to one).
     *
     * @return \App\Entity\Participant
     */
    public function getParticipant()
    {
        return $this->participant;
    }

    public function __sleep()
    {
        return ['id', 'question_id', 'reponse', 'participant_id'];
    }
}
