<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2017-02-09 11:20:18.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace App\Entity;

use Doctrine\ORM\Mapping\Column;
use Doctrine\ORM\Mapping\GeneratedValue;
use Doctrine\ORM\Mapping\Id;

/**
 * App\Entity\IntrigueHasObjectif.
 *
 * @Table(name="intrigue_has_objectif", indexes={@Index(name="fk_intrigue_has_objectif_objectif1_idx", columns={"objectif_id"}), @Index(name="fk_intrigue_has_objectif_intrigue1_idx", columns={"intrigue_id"})})
 *
 * @InheritanceType("SINGLE_TABLE")
 *
 * @DiscriminatorColumn(name="discr", type="string")
 *
 * @DiscriminatorMap({"base":"BaseIntrigueHasObjectif", "extended":"IntrigueHasObjectif"})
 */
class BaseIntrigueHasObjectif
{
    #[Id, Column(type: \Doctrine\DBAL\Types\Types::INTEGER, options: ['unsigned' => true]), GeneratedValue(strategy: 'AUTO')]
    protected ?int $id = null;

    /**
     * @ManyToOne(targetEntity="Intrigue", inversedBy="intrigueHasObjectifs", cascade={"persist", "remove"})
     *
     * @JoinColumn(name="intrigue_id", referencedColumnName="id", nullable=false)
     */
    protected $intrigue;

    /**
     * @ManyToOne(targetEntity="Objectif", inversedBy="intrigueHasObjectifs", cascade={"persist", "remove"})
     *
     * @JoinColumn(name="objectif_id", referencedColumnName="id", nullable=false)
     */
    protected $objectif;

    public function __construct()
    {
    }

    /**
     * Set the value of id.
     *
     * @param int $id
     *
     * @return \App\Entity\IntrigueHasObjectif
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set Intrigue entity (many to one).
     *
     * @return \App\Entity\IntrigueHasObjectif
     */
    public function setIntrigue(Intrigue $intrigue = null)
    {
        $this->intrigue = $intrigue;

        return $this;
    }

    /**
     * Get Intrigue entity (many to one).
     *
     * @return \App\Entity\Intrigue
     */
    public function getIntrigue()
    {
        return $this->intrigue;
    }

    /**
     * Set Objectif entity (many to one).
     *
     * @return \App\Entity\IntrigueHasObjectif
     */
    public function setObjectif(Objectif $objectif = null)
    {
        $this->objectif = $objectif;

        return $this;
    }

    /**
     * Get Objectif entity (many to one).
     *
     * @return \App\Entity\Objectif
     */
    public function getObjectif()
    {
        return $this->objectif;
    }

    public function __sleep()
    {
        return ['id', 'intrigue_id', 'objectif_id'];
    }
}
