<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2017-01-08 07:36:50.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace App\Entity;

/**
 * App\Entity\Debriefing.
 *
 * @Entity(repositoryClass="LarpManager\Repository\DebriefingRepository")
 */
class Debriefing extends BaseDebriefing
{
    /**
     * Définir la date de création et la date de mise à jour lors de la création d'un nouveau debriefing.
     */
    public function __construct()
    {
        parent::__construct();
        $this->setUpdateDate(new \DateTime('NOW'));
        $this->setCreationDate(new \DateTime('NOW'));
    }

    public function getPrintTitre(): ?string
    {
        return preg_replace('/[^a-z0-9]+/', '_', strtolower($this->getTitre()));
    }
}
