<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2017-01-20 16:00:48.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace App\Entity;

use App\Entity\BaseGroupeHasIngredient;

/**
 * App\Entity\GroupeHasIngredient
 *
 */
class GroupeHasIngredient extends BaseGroupeHasIngredient
{
}