<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2016-09-07 15:49:37.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;

/**
 * App\Entity\GroupeGn.
 *
 * @Entity(repositoryClass="LarpManager\Repository\GroupeGnRepository")
 */
class GroupeGn extends BaseGroupeGn
{
    public function __construct()
    {
        $this->agents ??= 0;
        $this->sieges ??= 0;
        $this->initiative ??= 0;
        $this->bateaux ??= 0;
    }

    /**
     * Défini le responsable de cette session de jeu.
     */
    public function setResponsable(Participant $participant): static
    {
        $this->setParticipant($participant);

        return $this;
    }

    /**
     * Fourni le responsable de cette session de jeu.
     */
    public function getResponsable()
    {
        return $this->getParticipant();
    }

    /**
     * Supprime le responsable de cette session de jeu.
     */
    public function setResponsableNull()
    {
        return $this->setParticipant(null);
    }

    /**
     * Fourni la liste des personnages de cette session de jeu.
     */
    public function getPersonnages(): ArrayCollection
    {
        $personnages = new ArrayCollection();

        foreach ($this->getParticipants() as $participant) {
            if ($participant->getPersonnage()) {
                $personnages[] = $participant->getPersonnage();
            }
        }

        return $personnages;
    }

    public function addAgent(): static
    {
        ++$this->agents;

        return $this;
    }

    public function addBateau(): static
    {
        ++$this->bateaux;

        return $this;
    }
}
