<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.3 (doctrine2-annotation) on 2019-11-04 14:25:48.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace App\Entity;

use App\Entity\BaseGroupeLangue;

/**
 * App\Entity\GroupeLangue
 *
 * @Entity(repositoryClass="LarpManager\Repository\GroupeLangueRepository")
 */
class GroupeLangue extends BaseGroupeLangue
{
}