<?php

/**
 * Generated by Kevin F.
 */

namespace App\Entity;

use App\Entity\BaseGroupeGnOrdre;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * App\Entity\GroupeGnOrdre
 *
 * @Entity(repositoryClass="LarpManager\Repository\GroupeGnOrdreRepository")
 */
class GroupeGnOrdre extends BaseGroupeGnOrdre
{

}