<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2017-05-13 16:49:12.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace App\Entity;

use App\Entity\BaseIntrigueHasLieu;

/**
 * App\Entity\IntrigueHasLieu
 *
 */
class IntrigueHasLieu extends BaseIntrigueHasLieu
{
}