<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2017-01-05 11:10:17.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace App\Entity;

use App\Entity\BaseIntrigueHasEvenement;

/**
 * App\Entity\IntrigueHasEvenement
 *
 */
class IntrigueHasEvenement extends BaseIntrigueHasEvenement
{
}