<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2017-01-04 12:11:54.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace App\Entity;

/**
 * App\Entity\Intrigue.
 *
 * @Entity(repositoryClass="LarpManager\Repository\IntrigueRepository")
 */
class Intrigue extends BaseIntrigue
{
    /**
     * Constructeur. Met en place la date de création et de mise à jour de l'intrigue.
     */
    public function __construct()
    {
        $this->setDateCreation(new \DateTime('NOW'));
        $this->setDateUpdate(new \DateTime('NOW'));
        parent::__construct();
    }
}
