<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2017-01-04 14:18:21.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace App\Entity;

use App\Entity\BaseIntrigueHasGroupe;

/**
 * App\Entity\IntrigueHasGroupe
 *
 */
class IntrigueHasGroupe extends BaseIntrigueHasGroupe
{
}