<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2017-02-09 10:47:30.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace App\Entity;

use App\Entity\BasePersonnageRessource;

/**
 * App\Entity\PersonnageRessource
 *
 */
class PersonnageRessource extends BasePersonnageRessource
{
}