<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2017-01-04 12:11:57.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace App\Entity;

use App\Entity\BaseRelecture;

/**
 * App\Entity\Relecture
 *
 */
class Relecture extends BaseRelecture
{
	public function __construct()
	{
		$this->setDate(new \Datetime('NOW'));
		parent::__construct();
	}
}