<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2017-08-01 16:51:53.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace App\Entity;

use App\Entity\BaseReligionDescription;

/**
 * App\Entity\ReligionDescription
 *
 */
class ReligionDescription extends BaseReligionDescription
{
}