<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2017-01-09 10:51:56.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace App\Entity;

/**
 * App\Entity\Rumeur.
 *
 * @Entity(repositoryClass="LarpManager\Repository\RumeurRepository")
 */
class Rumeur extends BaseRumeur
{
    /**
     * Constructeur. Met en place la date de création et de mise à jour de la rumeur.
     */
    public function __construct()
    {
        $this->setCreationDate(new \DateTime('NOW'));
        $this->setUpdateDate(new \DateTime('NOW'));
        parent::__construct();
    }

    public function getVisibility(): string
    {
        return match (parent::getVisibility()) {
            'disponible' => 'Non disponible',
            default => 'Brouillon',
        };
    }
}
