<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2017-07-02 10:39:31.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace App\Entity;

use App\Entity\BaseTechnologie;

/**
 * App\Entity\Technologie
 *
 * @Entity(repositoryClass="LarpManager\Repository\TechnologieRepository")
 */
class Technologie extends BaseTechnologie
{

    public function getPrintLabel()
	{
		return preg_replace('/[^a-z0-9]+/', '_', strtolower($this->getLabel()));
	}
}