<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260304174243 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Schema alignment phase 2: username VARCHAR(100), salt NOT NULL, DROP is_enabled, unsigned IDs, plus accumulated DEV→PROD drift. REQUIRES Version20260303150041 to have run first.';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE background CHANGE visibility visibility VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE billet CHANGE label label VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE billet RENAME INDEX fk_billet_user1_idx TO fk_billet_user1');
        $this->addSql('ALTER TABLE bonus CHANGE json_data json_data JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE competence CHANGE documentUrl documentUrl TINYTEXT DEFAULT NULL');
        $this->addSql('DROP INDEX `primary` ON competence_attribute');
        $this->addSql('ALTER TABLE competence_attribute ADD PRIMARY KEY (competence_id, attribute_type_id, value)');
        $this->addSql('ALTER TABLE connaissance CHANGE label label VARCHAR(45) NOT NULL, CHANGE contraintes contraintes LONGTEXT DEFAULT NULL, CHANGE documentUrl documentUrl VARCHAR(45) DEFAULT NULL, CHANGE niveau niveau INT NOT NULL, CHANGE discr discr VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE culture CHANGE id id INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE debriefing CHANGE player_id player_id INT UNSIGNED NOT NULL');
        $this->addSql('ALTER TABLE debriefing ADD CONSTRAINT FK_CB81225E99E6F5DF FOREIGN KEY (player_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE debriefing RENAME INDEX fk_debriefing_player1_idx TO IDX_CB81225E99E6F5DF');
        $this->addSql('ALTER TABLE document CHANGE creation_date creation_date DATETIME DEFAULT NULL, CHANGE update_date update_date DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE evenement CHANGE id id INT AUTO_INCREMENT NOT NULL');
        $this->addSql('DROP INDEX fk_experience_usage_personnage1_idx ON experience_usage');
        $this->addSql('CREATE INDEX IDX_B3B922665E315342 ON experience_usage (personnage_id)');
        $this->addSql('CREATE INDEX fk_experience_usage_personnage1_idx ON experience_usage (competence_id)');
        $this->addSql('ALTER TABLE formulaire CHANGE id id INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE gn CHANGE date_jeu date_jeu INT DEFAULT NULL');
        $this->addSql('ALTER TABLE groupe CHANGE territoire_id territoire_id INT NOT NULL, CHANGE description_membres description_membres LONGTEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE groupe_has_item CHANGE item_id item_id INT NOT NULL');
        $this->addSql('ALTER TABLE groupe_allie CHANGE message_allie message_allie VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE groupe_gn CHANGE responsable_id responsable_id INT NOT NULL, CHANGE place_available place_available INT NOT NULL, CHANGE agents agents INT NOT NULL, CHANGE bateaux bateaux INT NOT NULL, CHANGE sieges sieges INT NOT NULL, CHANGE initiative initiative INT NOT NULL');
        $this->addSql('ALTER TABLE groupe_gn ADD CONSTRAINT FK_413F11C8EAED05C FOREIGN KEY (diplomate_id) REFERENCES personnage (id)');
        $this->addSql('CREATE INDEX IDX_413F11C8EAED05C ON groupe_gn (diplomate_id)');
        $this->addSql('ALTER TABLE groupe_gn_ordre CHANGE groupe_gn_id groupe_gn_id INT NOT NULL, CHANGE cible_id cible_id INT NOT NULL');
        $this->addSql('ALTER TABLE groupe_has_ingredient CHANGE groupe_id groupe_id INT DEFAULT NULL, CHANGE ingredient_id ingredient_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE groupe_has_ressource CHANGE groupe_id groupe_id INT DEFAULT NULL, CHANGE ressource_id ressource_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE groupe_langue CHANGE label label VARCHAR(180) NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F86989B4EA750E8 ON groupe_langue (label)');
        $this->addSql('ALTER TABLE heroisme_history CHANGE personnage_id personnage_id INT DEFAULT NULL, CHANGE date date DATETIME NOT NULL, CHANGE explication explication VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE ingredient CHANGE description description VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE intrigue CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE resolution resolution LONGTEXT NOT NULL');
        $this->addSql('ALTER TABLE intrigue_has_document CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE intrigue_id intrigue_id INT NOT NULL');
        $this->addSql('ALTER TABLE intrigue_has_evenement CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE intrigue_id intrigue_id INT DEFAULT NULL, CHANGE evenement_id evenement_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE intrigue_has_groupe CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE intrigue_id intrigue_id INT DEFAULT NULL, CHANGE groupe_id groupe_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE intrigue_has_groupe_secondaire CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE intrigue_id intrigue_id INT NOT NULL');
        $this->addSql('ALTER TABLE intrigue_has_lieu CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE intrigue_id intrigue_id INT NOT NULL');
        $this->addSql('ALTER TABLE intrigue_has_modification CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE intrigue_id intrigue_id INT NOT NULL');
        $this->addSql('ALTER TABLE intrigue_has_objectif CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE intrigue_id intrigue_id INT NOT NULL, CHANGE objectif_id objectif_id INT NOT NULL');
        $this->addSql('ALTER TABLE item CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE quality_id quality_id INT DEFAULT NULL, CHANGE statut_id statut_id INT NOT NULL');
        $this->addSql('ALTER TABLE langue ADD CONSTRAINT FK_9357758E7A3969FA FOREIGN KEY (groupe_langue_id) REFERENCES groupe_langue (id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9AEACC134F2FFF1C ON level (`index`)');
        $this->addSql('ALTER TABLE lignees CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE description description LONGTEXT DEFAULT NULL, CHANGE discr discr VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE localisation CHANGE `precision` `precision` VARCHAR(450) NOT NULL');
        $this->addSql('ALTER TABLE loi CHANGE id id INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE message CHANGE lu lu TINYINT(1) NOT NULL');
        $this->addSql('ALTER TABLE notification CHANGE id id INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE notification RENAME INDEX fk_notification_user1_idx TO IDX_BF5476CAA76ED395');
        $this->addSql('ALTER TABLE objectif CHANGE id id INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE objet CHANGE proprietaire_id proprietaire_id INT NOT NULL, CHANGE responsable_id responsable_id INT UNSIGNED NOT NULL, CHANGE description description VARCHAR(45) DEFAULT NULL');
        $this->addSql('ALTER TABLE objet_carac CHANGE couleur couleur VARCHAR(6) DEFAULT NULL');
        $this->addSql('ALTER TABLE origine_bonus DROP FOREIGN KEY FK_BE693547D0F97A8');
        $this->addSql('DROP INDEX bonus_territoire ON origine_bonus');
        $this->addSql('ALTER TABLE origine_bonus CHANGE status status VARCHAR(36) DEFAULT NULL, CHANGE creation_date creation_date DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE origine_bonus ADD CONSTRAINT FK_BE693547D0F97A8 FOREIGN KEY (territoire_id) REFERENCES territoire (id)');
        $this->addSql('ALTER TABLE origine_bonus RENAME INDEX idx_be69354769545666 TO fk_bonus_idx');
        $this->addSql('ALTER TABLE origine_bonus RENAME INDEX idx_be693547d0f97a8 TO fk_territoire_idx');
        $this->addSql('ALTER TABLE participant CHANGE personnage_secondaire_id personnage_secondaire_id INT NOT NULL');
        $this->addSql('ALTER TABLE participant RENAME INDEX fk_joueur_gn_gn1_idx TO IDX_D79F6B11AFC9C052');
        $this->addSql('ALTER TABLE participant RENAME INDEX fk_joueur_gn_user1_idx TO IDX_D79F6B11A76ED395');
        $this->addSql('ALTER TABLE participant RENAME INDEX fk_participant_personnage_secondaire1_idx TO IDX_D79F6B11E6917FB3');
        $this->addSql('ALTER TABLE participant RENAME INDEX fk_participant_personnage1_idx TO IDX_D79F6B115E315342');
        $this->addSql('ALTER TABLE participant RENAME INDEX fk_participant_billet1_idx TO IDX_D79F6B1144973C78');
        $this->addSql('ALTER TABLE participant RENAME INDEX fk_participant_groupe_gn1_idx TO IDX_D79F6B11FA640E02');
        $this->addSql('ALTER TABLE participant_potions_depart RENAME INDEX idx_d485198a5e315343 TO IDX_E4DE0E59D1C3019');
        $this->addSql('ALTER TABLE participant_potions_depart RENAME INDEX idx_d485198a7126b349 TO IDX_E4DE0E57126B348');
        $this->addSql('ALTER TABLE participant_has_restauration CHANGE id id INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE personnage CHANGE groupe_id groupe_id INT NOT NULL, CHANGE territoire_id territoire_id INT NOT NULL, CHANGE user_id user_id INT UNSIGNED NOT NULL');
        $this->addSql('ALTER TABLE personnage_has_item CHANGE item_id item_id INT NOT NULL');
        $this->addSql('DROP INDEX `primary` ON personnages_prieres');
        $this->addSql('ALTER TABLE personnages_prieres ADD PRIMARY KEY (personnage_id, priere_id)');
        $this->addSql('ALTER TABLE personnages_connaissances MODIFY id INT UNSIGNED NOT NULL');
        $this->addSql('DROP INDEX `primary` ON personnages_connaissances');
        $this->addSql('ALTER TABLE personnages_connaissances DROP id, DROP discr, CHANGE connaissance_id connaissance_id INT UNSIGNED NOT NULL');
        $this->addSql('ALTER TABLE personnages_connaissances ADD PRIMARY KEY (personnage_id, connaissance_id)');
        $this->addSql('ALTER TABLE personnages_connaissances RENAME INDEX fk_personnages_connaissances TO IDX_3F5B4C1D5E315342');
        $this->addSql('ALTER TABLE personnages_connaissances RENAME INDEX fk_connaissances TO IDX_3F5B4C1D68A34E8E');
        $this->addSql('ALTER TABLE personnage_apprentissage CHANGE competence_id competence_id INT NOT NULL');
        $this->addSql('ALTER TABLE personnage_background CHANGE text text VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE personnage_background RENAME INDEX fk_personnage_background_gn1_idx TO IDX_273D6F45AFC9C052');
        $this->addSql('DROP INDEX UNIQ_35CB734069545666 ON personnage_bonus');
        $this->addSql('ALTER TABLE personnage_bonus CHANGE personnage_id personnage_id INT NOT NULL');
        $this->addSql('ALTER TABLE personnage_bonus RENAME INDEX idx_35cb734069545666 TO fk_bonus_idx');
        $this->addSql('ALTER TABLE personnage_bonus RENAME INDEX idx_35cb73405e315342 TO fk_personnage_idx');
        $this->addSql('ALTER TABLE personnage_has_question CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE question_id question_id INT NOT NULL');
        $this->addSql('ALTER TABLE personnage_has_token CHANGE id id INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE personnage_ingredient CHANGE id id INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE personnage_ressource CHANGE id id INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE personnages_chronologie CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE evenement evenement VARCHAR(255) NOT NULL, CHANGE discr discr VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE personnages_chronologie RENAME INDEX fk_6ecc33456843 TO IDX_3F01054A5E315342');
        $this->addSql('ALTER TABLE personnages_lignee CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE parent1_id parent1_id INT NOT NULL, CHANGE parent2_id parent2_id INT NOT NULL, CHANGE lignee_id lignee_id INT NOT NULL, CHANGE discr discr VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE personnages_lignee RENAME INDEX fk_6ecc33456847 TO IDX_E0C9F0805E315342');
        $this->addSql('ALTER TABLE personnages_lignee RENAME INDEX fk_6ecc33456844 TO IDX_E0C9F080861B2665');
        $this->addSql('ALTER TABLE personnages_lignee RENAME INDEX fk_6ecc33456845 TO IDX_E0C9F08094AE898B');
        $this->addSql('ALTER TABLE personnages_lignee RENAME INDEX fk_6ecc33456846 TO IDX_E0C9F0802B3F22E1');
        $this->addSql('ALTER TABLE photo CHANGE name name VARCHAR(45) DEFAULT NULL, CHANGE extension extension VARCHAR(45) DEFAULT NULL, CHANGE creation_date creation_date DATETIME DEFAULT NULL, CHANGE filename filename VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE priere CHANGE sphere_id sphere_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE pugilat_history CHANGE date date DATETIME NOT NULL');
        $this->addSql('ALTER TABLE qr_code_scan_log CHANGE item_id item_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE quality_valeur CHANGE id id INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE question CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE text text VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE rangement CHANGE localisation_id localisation_id INT NOT NULL');
        $this->addSql('ALTER TABLE relecture CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE intrigue_id intrigue_id INT NOT NULL');
        $this->addSql('ALTER TABLE religion CHANGE description description VARCHAR(255) DEFAULT NULL, CHANGE description_orga description_orga VARCHAR(255) DEFAULT NULL, CHANGE description_fervent description_fervent VARCHAR(255) DEFAULT NULL, CHANGE description_pratiquant description_pratiquant VARCHAR(255) DEFAULT NULL, CHANGE description_fanatique description_fanatique VARCHAR(255) DEFAULT NULL, CHANGE secret secret TINYINT(1) DEFAULT 0');
        $this->addSql('ALTER TABLE religion_description CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE description description VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE religion_level CHANGE description description VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE renomme_history CHANGE explication explication VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE reponse CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE question_id question_id INT NOT NULL');
        $this->addSql('ALTER TABLE restauration CHANGE description description VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE rule CHANGE description description VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE rumeur CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE territoire_id territoire_id INT NOT NULL, CHANGE text text VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE secondary_group_type CHANGE description description LONGTEXT NOT NULL');
        $this->addSql('ALTER TABLE sort CHANGE description description VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE sorts CHANGE description description VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE technologie DROP FOREIGN KEY FK_technologie_competence_family');
        $this->addSql('ALTER TABLE technologie CHANGE description description TEXT NOT NULL');
        // FK_AD813674F7EB2017 already added by Version20260303150041 — do not re-add
        $this->addSql('ALTER TABLE technologie RENAME INDEX fk_technologie_competence_family TO IDX_AD813674F7EB2017');
        $this->addSql('ALTER TABLE technologies_ressources DROP FOREIGN KEY FK_B15E3D68261A27D2');
        $this->addSql('ALTER TABLE technologies_ressources CHANGE technologie_id technologie_id INT UNSIGNED DEFAULT NULL, CHANGE ressource_id ressource_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE technologies_ressources ADD CONSTRAINT FK_B15E3D68261A27D2 FOREIGN KEY (technologie_id) REFERENCES technologie (id)');
        $this->addSql('ALTER TABLE technologies_ressources RENAME INDEX fk_technologies_ressources_idx TO IDX_B15E3D68261A27D2');
        $this->addSql('ALTER TABLE technologies_ressources RENAME INDEX fk_b15e3d68fc6cd52a TO IDX_B15E3D68FC6CD52A');
        $this->addSql('ALTER TABLE territoire CHANGE appelation_id appelation_id INT DEFAULT NULL, CHANGE culture_id culture_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE territoire RENAME INDEX fk_zone_politique_zone_politique1_idx TO fk_territoire_territoire1_idx');
        $this->addSql('ALTER TABLE territoire_has_loi CHANGE loi_id loi_id INT NOT NULL');
        $this->addSql('ALTER TABLE token CHANGE description description VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D649E6917FB3');
        $this->addSql('ALTER TABLE user DROP is_enabled, CHANGE password password VARCHAR(255) NOT NULL, CHANGE creation_date creation_date DATETIME DEFAULT NULL, CHANGE username username VARCHAR(100) NOT NULL, CHANGE timePasswordResetRequested timePasswordResetRequested INT DEFAULT NULL, CHANGE pwd pwd VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D649E6917FB3 FOREIGN KEY (personnage_secondaire_id) REFERENCES personnage_secondaire (id)');
        $this->addSql('ALTER TABLE messenger_messages CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', CHANGE available_at available_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', CHANGE delivered_at delivered_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE background CHANGE visibility visibility VARCHAR(45) DEFAULT NULL');
        $this->addSql('ALTER TABLE billet CHANGE label label VARCHAR(45) NOT NULL');
        $this->addSql('ALTER TABLE billet RENAME INDEX fk_billet_user1 TO fk_billet_user1_idx');
        $this->addSql('ALTER TABLE bonus CHANGE json_data json_data JSON DEFAULT NULL COLLATE `utf8mb4_bin`');
        $this->addSql('ALTER TABLE competence CHANGE documentUrl documentUrl VARCHAR(45) DEFAULT NULL');
        $this->addSql('DROP INDEX `PRIMARY` ON competence_attribute');
        $this->addSql('ALTER TABLE competence_attribute ADD PRIMARY KEY (competence_id, attribute_type_id)');
        $this->addSql('ALTER TABLE connaissance CHANGE label label VARCHAR(45) NOT NULL COLLATE `utf8mb3_unicode_ci`, CHANGE contraintes contraintes LONGTEXT DEFAULT NULL COLLATE `utf8mb3_unicode_ci`, CHANGE documentUrl documentUrl VARCHAR(255) DEFAULT NULL, CHANGE niveau niveau INT UNSIGNED DEFAULT 1 NOT NULL, CHANGE discr discr VARCHAR(45) DEFAULT \'extended\' NOT NULL COLLATE `utf8mb3_unicode_ci`');
        $this->addSql('ALTER TABLE culture CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE debriefing DROP FOREIGN KEY FK_CB81225E99E6F5DF');
        $this->addSql('ALTER TABLE debriefing CHANGE player_id player_id INT UNSIGNED DEFAULT NULL');
        $this->addSql('ALTER TABLE debriefing RENAME INDEX idx_cb81225e99e6f5df TO fk_debriefing_player1_idx');
        $this->addSql('ALTER TABLE document CHANGE creation_date creation_date DATETIME NOT NULL, CHANGE update_date update_date DATETIME NOT NULL');
        $this->addSql('ALTER TABLE evenement CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL');
        $this->addSql('DROP INDEX IDX_B3B922665E315342 ON experience_usage');
        $this->addSql('DROP INDEX fk_experience_usage_personnage1_idx ON experience_usage');
        $this->addSql('CREATE INDEX fk_experience_usage_personnage1_idx ON experience_usage (personnage_id)');
        $this->addSql('ALTER TABLE formulaire CHANGE id id INT NOT NULL');
        $this->addSql('ALTER TABLE gn CHANGE date_jeu date_jeu INT UNSIGNED DEFAULT NULL');
        $this->addSql('ALTER TABLE groupe CHANGE territoire_id territoire_id INT DEFAULT NULL, CHANGE description_membres description_membres TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE groupe_allie CHANGE message_allie message_allie LONGTEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE groupe_gn DROP FOREIGN KEY FK_413F11C8EAED05C');
        $this->addSql('DROP INDEX IDX_413F11C8EAED05C ON groupe_gn');
        $this->addSql('ALTER TABLE groupe_gn CHANGE responsable_id responsable_id INT DEFAULT NULL, CHANGE place_available place_available INT DEFAULT NULL, CHANGE agents agents INT DEFAULT 0 NOT NULL, CHANGE bateaux bateaux INT DEFAULT 0 NOT NULL, CHANGE sieges sieges INT DEFAULT 0 NOT NULL, CHANGE initiative initiative INT DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE groupe_gn_ordre CHANGE groupe_gn_id groupe_gn_id INT DEFAULT NULL, CHANGE cible_id cible_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE groupe_has_ingredient CHANGE groupe_id groupe_id INT NOT NULL, CHANGE ingredient_id ingredient_id INT NOT NULL');
        $this->addSql('ALTER TABLE groupe_has_item CHANGE item_id item_id INT UNSIGNED NOT NULL');
        $this->addSql('ALTER TABLE groupe_has_ressource CHANGE groupe_id groupe_id INT NOT NULL, CHANGE ressource_id ressource_id INT NOT NULL');
        $this->addSql('DROP INDEX UNIQ_F86989B4EA750E8 ON groupe_langue');
        $this->addSql('ALTER TABLE groupe_langue CHANGE label label VARCHAR(100) NOT NULL');
        $this->addSql('ALTER TABLE heroisme_history CHANGE personnage_id personnage_id INT NOT NULL, CHANGE date date DATE NOT NULL, CHANGE explication explication LONGTEXT NOT NULL');
        $this->addSql('ALTER TABLE ingredient CHANGE description description LONGTEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE intrigue CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE resolution resolution LONGTEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE intrigue_has_document CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE intrigue_id intrigue_id INT UNSIGNED NOT NULL');
        $this->addSql('ALTER TABLE intrigue_has_evenement CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE intrigue_id intrigue_id INT UNSIGNED NOT NULL, CHANGE evenement_id evenement_id INT UNSIGNED NOT NULL');
        $this->addSql('ALTER TABLE intrigue_has_groupe CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE intrigue_id intrigue_id INT UNSIGNED NOT NULL, CHANGE groupe_id groupe_id INT NOT NULL');
        $this->addSql('ALTER TABLE intrigue_has_groupe_secondaire CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE intrigue_id intrigue_id INT UNSIGNED NOT NULL');
        $this->addSql('ALTER TABLE intrigue_has_lieu CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE intrigue_id intrigue_id INT UNSIGNED NOT NULL');
        $this->addSql('ALTER TABLE intrigue_has_modification CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE intrigue_id intrigue_id INT UNSIGNED NOT NULL');
        $this->addSql('ALTER TABLE intrigue_has_objectif CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE intrigue_id intrigue_id INT UNSIGNED NOT NULL, CHANGE objectif_id objectif_id INT UNSIGNED NOT NULL');
        $this->addSql('ALTER TABLE item CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE quality_id quality_id INT NOT NULL, CHANGE statut_id statut_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE langue DROP FOREIGN KEY FK_9357758E7A3969FA');
        $this->addSql('DROP INDEX UNIQ_9AEACC134F2FFF1C ON level');
        $this->addSql('ALTER TABLE lignees CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE description description TEXT DEFAULT NULL, CHANGE discr discr VARCHAR(255) DEFAULT \'extended\' NOT NULL');
        $this->addSql('ALTER TABLE localisation CHANGE `precision` `precision` VARCHAR(450) DEFAULT NULL');
        $this->addSql('ALTER TABLE loi CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE message CHANGE lu lu TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE messenger_messages CHANGE created_at created_at DATETIME NOT NULL, CHANGE available_at available_at DATETIME NOT NULL, CHANGE delivered_at delivered_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE notification CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE notification RENAME INDEX idx_bf5476caa76ed395 TO fk_notification_user1_idx');
        $this->addSql('ALTER TABLE objectif CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE objet CHANGE proprietaire_id proprietaire_id INT DEFAULT NULL, CHANGE responsable_id responsable_id INT UNSIGNED DEFAULT NULL, CHANGE description description VARCHAR(450) DEFAULT NULL');
        $this->addSql('ALTER TABLE objet_carac CHANGE couleur couleur VARCHAR(45) DEFAULT NULL');
        $this->addSql('ALTER TABLE origine_bonus DROP FOREIGN KEY FK_BE693547D0F97A8');
        $this->addSql('ALTER TABLE origine_bonus CHANGE creation_date creation_date DATETIME NOT NULL, CHANGE status status VARCHAR(32) DEFAULT NULL');
        $this->addSql('ALTER TABLE origine_bonus ADD CONSTRAINT FK_BE693547D0F97A8 FOREIGN KEY (territoire_id) REFERENCES territoire (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('CREATE UNIQUE INDEX bonus_territoire ON origine_bonus (bonus_id, territoire_id)');
        $this->addSql('ALTER TABLE origine_bonus RENAME INDEX fk_bonus_idx TO IDX_BE69354769545666');
        $this->addSql('ALTER TABLE origine_bonus RENAME INDEX fk_territoire_idx TO IDX_BE693547D0F97A8');
        $this->addSql('ALTER TABLE participant CHANGE personnage_secondaire_id personnage_secondaire_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE participant RENAME INDEX idx_d79f6b11afc9c052 TO fk_joueur_gn_gn1_idx');
        $this->addSql('ALTER TABLE participant RENAME INDEX idx_d79f6b11a76ed395 TO fk_joueur_gn_user1_idx');
        $this->addSql('ALTER TABLE participant RENAME INDEX idx_d79f6b11e6917fb3 TO fk_participant_personnage_secondaire1_idx');
        $this->addSql('ALTER TABLE participant RENAME INDEX idx_d79f6b115e315342 TO fk_participant_personnage1_idx');
        $this->addSql('ALTER TABLE participant RENAME INDEX idx_d79f6b1144973c78 TO fk_participant_billet1_idx');
        $this->addSql('ALTER TABLE participant RENAME INDEX idx_d79f6b11fa640e02 TO fk_participant_groupe_gn1_idx');
        $this->addSql('ALTER TABLE participant_has_restauration CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE participant_potions_depart RENAME INDEX idx_e4de0e59d1c3019 TO IDX_D485198A5E315343');
        $this->addSql('ALTER TABLE participant_potions_depart RENAME INDEX idx_e4de0e57126b348 TO IDX_D485198A7126B349');
        $this->addSql('ALTER TABLE personnage CHANGE groupe_id groupe_id INT DEFAULT NULL, CHANGE territoire_id territoire_id INT DEFAULT NULL, CHANGE user_id user_id INT UNSIGNED DEFAULT NULL');
        $this->addSql('ALTER TABLE personnage_apprentissage CHANGE competence_id competence_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE personnage_background CHANGE text text LONGTEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE personnage_background RENAME INDEX idx_273d6f45afc9c052 TO fk_personnage_background_gn1_idx');
        $this->addSql('ALTER TABLE personnage_bonus CHANGE personnage_id personnage_id INT DEFAULT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_35CB734069545666 ON personnage_bonus (bonus_id, personnage_id)');
        $this->addSql('ALTER TABLE personnage_bonus RENAME INDEX fk_personnage_idx TO IDX_35CB73405E315342');
        $this->addSql('ALTER TABLE personnage_bonus RENAME INDEX fk_bonus_idx TO IDX_35CB734069545666');
        $this->addSql('ALTER TABLE personnage_has_item CHANGE item_id item_id INT UNSIGNED NOT NULL');
        $this->addSql('ALTER TABLE personnage_has_question CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE question_id question_id INT UNSIGNED NOT NULL');
        $this->addSql('ALTER TABLE personnage_has_token CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE personnage_ingredient CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE personnage_ressource CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE personnages_chronologie CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE evenement evenement VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, CHANGE discr discr VARCHAR(255) CHARACTER SET utf8mb3 DEFAULT \'extended\' NOT NULL COLLATE `utf8mb3_unicode_ci`');
        $this->addSql('ALTER TABLE personnages_chronologie RENAME INDEX idx_3f01054a5e315342 TO FK_6ECC33456843');
        $this->addSql('ALTER TABLE personnages_connaissances ADD id INT UNSIGNED AUTO_INCREMENT NOT NULL, ADD discr VARCHAR(255) CHARACTER SET utf8mb3 DEFAULT \'extended\' NOT NULL COLLATE `utf8mb3_unicode_ci`, CHANGE connaissance_id connaissance_id INT UNSIGNED DEFAULT NULL, DROP PRIMARY KEY, ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE personnages_connaissances RENAME INDEX idx_3f5b4c1d5e315342 TO FK_PERSONNAGES_CONNAISSANCES');
        $this->addSql('ALTER TABLE personnages_connaissances RENAME INDEX idx_3f5b4c1d68a34e8e TO FK_CONNAISSANCES');
        $this->addSql('ALTER TABLE personnages_lignee CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE parent1_id parent1_id INT DEFAULT NULL, CHANGE parent2_id parent2_id INT DEFAULT NULL, CHANGE lignee_id lignee_id INT UNSIGNED DEFAULT NULL, CHANGE discr discr VARCHAR(255) CHARACTER SET utf8mb3 DEFAULT \'extended\' NOT NULL COLLATE `utf8mb3_unicode_ci`');
        $this->addSql('ALTER TABLE personnages_lignee RENAME INDEX idx_e0c9f0805e315342 TO FK_6ECC33456847');
        $this->addSql('ALTER TABLE personnages_lignee RENAME INDEX idx_e0c9f080861b2665 TO FK_6ECC33456844');
        $this->addSql('ALTER TABLE personnages_lignee RENAME INDEX idx_e0c9f08094ae898b TO FK_6ECC33456845');
        $this->addSql('ALTER TABLE personnages_lignee RENAME INDEX idx_e0c9f0802b3f22e1 TO FK_6ECC33456846');
        $this->addSql('DROP INDEX `PRIMARY` ON personnages_prieres');
        $this->addSql('ALTER TABLE personnages_prieres ADD PRIMARY KEY (priere_id, personnage_id)');
        $this->addSql('ALTER TABLE photo CHANGE name name VARCHAR(45) NOT NULL, CHANGE extension extension VARCHAR(45) NOT NULL, CHANGE creation_date creation_date DATETIME NOT NULL, CHANGE filename filename VARCHAR(100) NOT NULL');
        $this->addSql('ALTER TABLE priere CHANGE sphere_id sphere_id INT NOT NULL');
        $this->addSql('ALTER TABLE pugilat_history CHANGE date date DATE NOT NULL');
        $this->addSql('ALTER TABLE qr_code_scan_log CHANGE item_id item_id INT UNSIGNED DEFAULT NULL');
        $this->addSql('ALTER TABLE quality_valeur CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE question CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE text text LONGTEXT NOT NULL');
        $this->addSql('ALTER TABLE rangement CHANGE localisation_id localisation_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE relecture CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE intrigue_id intrigue_id INT UNSIGNED NOT NULL');
        $this->addSql('ALTER TABLE religion CHANGE description description LONGTEXT DEFAULT NULL, CHANGE description_orga description_orga LONGTEXT DEFAULT NULL, CHANGE description_fervent description_fervent LONGTEXT DEFAULT NULL, CHANGE description_pratiquant description_pratiquant LONGTEXT DEFAULT NULL, CHANGE description_fanatique description_fanatique LONGTEXT DEFAULT NULL, CHANGE secret secret TINYINT(1) DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE religion_description CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE description description LONGTEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE religion_level CHANGE description description LONGTEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE renomme_history CHANGE explication explication LONGTEXT NOT NULL');
        $this->addSql('ALTER TABLE reponse CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE question_id question_id INT UNSIGNED NOT NULL');
        $this->addSql('ALTER TABLE restauration CHANGE description description LONGTEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE rule CHANGE description description LONGTEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE rumeur CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE territoire_id territoire_id INT DEFAULT NULL, CHANGE text text LONGTEXT NOT NULL');
        $this->addSql('ALTER TABLE secondary_group_type CHANGE description description LONGTEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE sort CHANGE description description LONGTEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE sorts CHANGE description description LONGTEXT DEFAULT NULL');
        // FK_AD813674F7EB2017 was not added by this migration (added by Version20260303150041) — do not drop it here
        $this->addSql('ALTER TABLE technologie CHANGE description description LONGTEXT NOT NULL');
        $this->addSql('ALTER TABLE technologie ADD CONSTRAINT FK_technologie_competence_family FOREIGN KEY (competence_family_id) REFERENCES competence_family (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE technologie RENAME INDEX idx_ad813674f7eb2017 TO FK_technologie_competence_family');
        $this->addSql('ALTER TABLE technologies_ressources DROP FOREIGN KEY FK_B15E3D68261A27D2');
        $this->addSql('ALTER TABLE technologies_ressources CHANGE technologie_id technologie_id INT UNSIGNED NOT NULL, CHANGE ressource_id ressource_id INT NOT NULL');
        $this->addSql('ALTER TABLE technologies_ressources ADD CONSTRAINT FK_B15E3D68261A27D2 FOREIGN KEY (technologie_id) REFERENCES technologie (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE technologies_ressources RENAME INDEX idx_b15e3d68261a27d2 TO fk_technologies_ressources_idx');
        $this->addSql('ALTER TABLE technologies_ressources RENAME INDEX idx_b15e3d68fc6cd52a TO FK_B15E3D68FC6CD52A');
        $this->addSql('ALTER TABLE territoire CHANGE appelation_id appelation_id INT NOT NULL, CHANGE culture_id culture_id INT UNSIGNED DEFAULT NULL');
        $this->addSql('ALTER TABLE territoire RENAME INDEX fk_territoire_territoire1_idx TO fk_zone_politique_zone_politique1_idx');
        $this->addSql('ALTER TABLE territoire_has_loi CHANGE loi_id loi_id INT UNSIGNED NOT NULL');
        // territoire_quete FKs added by Version20260303150041, not this migration — do not drop them here
        $this->addSql('ALTER TABLE token CHANGE description description LONGTEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D649E6917FB3');
        $this->addSql('ALTER TABLE user ADD is_enabled TINYINT(1) DEFAULT NULL, CHANGE password password VARCHAR(255) DEFAULT NULL, CHANGE pwd pwd VARCHAR(255) DEFAULT NULL, CHANGE username username VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_bin`, CHANGE creation_date creation_date DATETIME NOT NULL, CHANGE timePasswordResetRequested timePasswordResetRequested INT UNSIGNED DEFAULT NULL');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D649E6917FB3 FOREIGN KEY (personnage_secondaire_id) REFERENCES personnage (id)');
    }
}
