
###
# curl -X POST -H "Content-Type: application/json" https://localhost/api/login_check -d '{"username":"johndoe","password":"test"}'
POST {{host}}/api/login_check
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{pwd}}"
}

> {%
    client.global.set("auth_token", response.body.token);
    client.log(response.body.token);
%}
###

### Authorization by token, part 2. Use token to authorize.
GET {{host}}/api/7/gdata.json
Authorization: Bearer {{auth_token}}
